import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-zinc-950 text-zinc-100 selection:bg-indigo-500/30 selection:text-indigo-200">
        <header className="sticky top-0 z-50 w-full border-b border-zinc-900 bg-zinc-950/80 backdrop-blur-md">
          <div className="max-w-4xl mx-auto px-4 h-16 flex items-center justify-between">
            <div className="flex items-center gap-2.5">
              <div className="w-6 h-6 rounded-md bg-gradient-to-tr from-indigo-500 to-violet-500 flex items-center justify-center shadow-lg shadow-indigo-500/20">
                <span className="text-white text-xs font-bold font-mono">✓</span>
              </div>
              <span className="font-semibold text-lg tracking-tight bg-gradient-to-r from-zinc-100 to-zinc-400 bg-clip-text text-transparent">
                AetherTodo
              </span>
            </div>
            <nav className="flex items-center gap-4 text-sm text-zinc-400">
              <span className="text-xs px-2 py-1 rounded bg-zinc-900 border border-zinc-800 text-zinc-500 font-mono">
                v1.0.0
              </span>
            </nav>
          </div>
        </header>

        <main className="flex-1 max-w-4xl mx-auto w-full px-4 py-8 flex flex-col">
          {children}
        </main>

        <footer className="border-t border-zinc-900 py-6">
          <div className="max-w-4xl mx-auto px-4 text-center text-xs text-zinc-600 font-mono">
            &copy; {new Date().getFullYear()} AetherTodo. Designed for visual excellence.
          </div>
        </footer>
      </body>
    </html>
  );
}
